name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List project files (debugging)
      run: ls -R 

    - name: Restore dependencies
      run: dotnet restore AutorizacionMiddleware/AutorizacionMiddleware.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore AutorizacionMiddleware/AutorizacionMiddleware.sln

    - name: Pack
      run: dotnet pack --configuration Release --output ./artifacts AutorizacionMiddleware/AutorizacionMiddleware.sln

    - uses: actions/upload-artifact@v4
      with:
        name: Autorizacion.Middleware
        if-no-files-found: error
        retention-days: 7
        path: artifacts/*.nupkg

  release:
    runs-on: ubuntu-latest    
    needs: build
    steps:  
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Download Artifacts 
      uses: actions/download-artifact@v4
      with:
        name: Autorizacion.Middleware
        path: ./artifacts
    
    - name: List Files
      run: ls -R ./artifacts
      
    - name: Prep packages
      run: dotnet nuget add source --username dmora233 --password ${{ secrets.PAQUETES_TOKEN }} --store-password-in-clear-text --name paquetes-sc701 "https://nuget.pkg.github.com/dmora233/index.json"

    - name: Verify NuGet Source
      run: dotnet nuget list source

    - name: Push package to GitHub packages 
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.PAQUETES_TOKEN }}  --source "paquetes-sc701" --skip-duplicate
