name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List Repository Structure
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore AutorizacionMiddleware/AutorizacionMiddleware.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore AutorizacionMiddleware/AutorizacionMiddleware.sln

    - name: Pack
      run: dotnet pack --configuration Release --output ./artifacts AutorizacionMiddleware/AutorizacionMiddleware.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutorizacionMiddleware
        path: artifacts/*.nupkg
        if-no-files-found: error
        retention-days: 7
